collections:
    projects:
      output: true

exclude:
    - package.json
    - webpack.config.js
    - package.lock.json
    - node_modules

include:
    - _data

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]